apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-storage-claim
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: welcome
        - name: MYSQL_DATABASE
          value: todo
        - name: MYSQL_USER
          value: todo
        - name: MYSQL_PASSWORD
          value: todo
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: db-storage