kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"