apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
spec:
  selector:
    matchLabels:
      app: todo-api
  replicas: 3
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: venkyramachandran82/todo-api
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_NAME
          value: todo
        - name: DB_USER
          value: todo
        - name: DB_PASSWORD
          value: todo
        - name: DB_SERVER
          value: mysql