apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
spec:
  selector:
    matchLabels:
      app: todo-api
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: venkyramachandran82/todo-api
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_NAME
          value: todo
        - name: DB_USER
          value: todo
        - name: DB_PASSWORD
          value: todo
        - name: DB_SERVER
          value: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: todo-api